package ByDan.Framework.Utils;

public enum ParameterType {
BIGDECIMAL,BINARYSTREAM,BLOB,BOOLEAN,BYTE,BYTES,CHARACTERSTREAM,CLOB,DATE,DOUBLE,FLOAT,INT,LONG,NCHARACTERSTREAM,NCLOB,NSTRING,NULL,
OBJECT,STRING,TIME,TIMESTAMP,NONE
}
